spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  springdoc:
    swagger-ui:
      path: /api/swagger-ui.html
    api-docs:
      path: /api/v3/api-docs

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create          # or update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always               # data.sql 실행을 항상 보장
      data-locations:
        - classpath:data.sql

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false